name: My Example Action 

on:
  push:  # Trigger on every push to any branch
  pull_request: # Trigger on pull requests

jobs:
  my_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: k.ashok2@straive.com - Run a script
        run: |
          echo "Hello from my action!"
          echo "Current date and time: $(date)"
          # You can add more commands here if needed

      - name: Another Step (Optional)
        run: echo "This is another step"
